services:
  oracle:
    container_name: oracledb
    image: 'container-registry.oracle.com/database/enterprise:latest'
    environment:
      - ORACLE_PASSWORD= aaa
    ports:
      - '1522:1521'
      - '5500:5500'
    volumes:
      - './data:/opt/oracle/oradata'
